name: Job Distribution Test

on:
  workflow_dispatch:
    inputs:
      total_jobs:
        description: 'Total jobs'
        type: number
        default: 20
      total_runners:
        description: 'Total runners'
        type: number
        default: 3

jobs:
  calculate_distribution:
    runs-on: ubuntu-latest
    outputs:
      group1_range: ${{ steps.calc.outputs.group1_range }}
      group2_range: ${{ steps.calc.outputs.group2_range }}
      group3_range: ${{ steps.calc.outputs.group3_range }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate Job Distribution
        id: calc
        run: |
          chmod +x scripts/calculate_distribution.sh
          ./scripts/calculate_distribution.sh ${{ github.event.inputs.total_jobs }} ${{ github.event.inputs.total_runners }}

  # 각 그룹별 실행 (GitHub-hosted runners 사용)
  group1_execution:
    needs: calculate_distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Group 1 Jobs
        run: |
          chmod +x scripts/execute_jobs.sh
          ./scripts/execute_jobs.sh "Group 1" "${{ needs.calculate_distribution.outputs.group1_range }}"

  group2_execution:
    needs: calculate_distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Group 2 Jobs
        run: |
          chmod +x scripts/execute_jobs.sh
          ./scripts/execute_jobs.sh "Group 2" "${{ needs.calculate_distribution.outputs.group2_range }}"

  group3_execution:
    needs: calculate_distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Group 3 Jobs
        run: |
          chmod +x scripts/execute_jobs.sh
          ./scripts/execute_jobs.sh "Group 3" "${{ needs.calculate_distribution.outputs.group3_range }}"
