name: Job Distribution Test

on:
  workflow_dispatch:
    inputs:
      total_jobs:
        description: 'Total jobs'
        type: number
        default: 20
      total_runners:
        description: 'Total runners'
        type: number
        default: 3

jobs:
  calculate_distribution:
    runs-on: ubuntu-latest
    outputs:
      groups_matrix: ${{ steps.calc.outputs.groups_matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate Job Distribution
        id: calc
        run: |
          chmod +x scripts/calculate_distribution.sh
          ./scripts/calculate_distribution.sh ${{ github.event.inputs.total_jobs }} ${{ github.event.inputs.total_runners }}

  # 동적 Matrix를 사용한 그룹별 실행
  group_execution:
    needs: calculate_distribution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: ${{ fromJson(needs.calculate_distribution.outputs.groups_matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Jobs for ${{ matrix.group.name }}
        run: |
          chmod +x scripts/execute_jobs.sh
          ./scripts/execute_jobs.sh "${{ matrix.group.name }}" "${{ matrix.group.range }}"
